---
abstract: 'Object oriented simple interface to fork()'
author:
  - 'Chad Granum <exodist7@gmail.com>'
build_requires:
  Test::More: 0.88
configure_requires:
  Module::Build: 0.36
generated_by: 'Module::Build version 0.3607'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Child
provides:
  Child:
    file: lib/Child.pm
    version: 0.008
  Child::IPC::Pipe:
    file: lib/Child/IPC/Pipe.pm
  Child::Link:
    file: lib/Child/Link.pm
  Child::Link::IPC:
    file: lib/Child/Link/IPC.pm
  Child::Link::IPC::Pipe:
    file: lib/Child/Link/IPC/Pipe.pm
  Child::Link::IPC::Pipe::Parent:
    file: lib/Child/Link/IPC/Pipe/Parent.pm
  Child::Link::IPC::Pipe::Proc:
    file: lib/Child/Link/IPC/Pipe/Proc.pm
  Child::Link::Parent:
    file: lib/Child/Link/Parent.pm
  Child::Link::Proc:
    file: lib/Child/Link/Proc.pm
  Child::Util:
    file: lib/Child/Util.pm
requires:
  Exporter: 5.57
  POSIX: 0
  perl: 5.006
resources:
  bugtracker: http://github.com/exodist/Child/issues
  homepage: http://open-exodus.net/projects/child
  license: http://dev.perl.org/licenses/
  repository: http://github.com/exodist/Child
version: 0.008
